//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servers.ProxyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyServiceReference.IProxyService")]
    public interface IProxyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetStationsWithBikes", ReplyAction="http://tempuri.org/IProxyService/GetStationsWithBikesResponse")]
        string GetStationsWithBikes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetStationsWithBikes", ReplyAction="http://tempuri.org/IProxyService/GetStationsWithBikesResponse")]
        System.Threading.Tasks.Task<string> GetStationsWithBikesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetStationsWithSpots", ReplyAction="http://tempuri.org/IProxyService/GetStationsWithSpotsResponse")]
        string GetStationsWithSpots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/GetStationsWithSpots", ReplyAction="http://tempuri.org/IProxyService/GetStationsWithSpotsResponse")]
        System.Threading.Tasks.Task<string> GetStationsWithSpotsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyServiceChannel : Servers.ProxyServiceReference.IProxyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyServiceClient : System.ServiceModel.ClientBase<Servers.ProxyServiceReference.IProxyService>, Servers.ProxyServiceReference.IProxyService {
        
        public ProxyServiceClient() {
        }
        
        public ProxyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStationsWithBikes() {
            return base.Channel.GetStationsWithBikes();
        }
        
        public System.Threading.Tasks.Task<string> GetStationsWithBikesAsync() {
            return base.Channel.GetStationsWithBikesAsync();
        }
        
        public string GetStationsWithSpots() {
            return base.Channel.GetStationsWithSpots();
        }
        
        public System.Threading.Tasks.Task<string> GetStationsWithSpotsAsync() {
            return base.Channel.GetStationsWithSpotsAsync();
        }
    }
}
